-- Migration reverted: These tables and columns are still in use by the application
-- DO NOT drop tables or columns that are actively referenced in the codebase
-- This migration has been intentionally left empty to preserve data integrity